fix whitespaces

diff --git a/bash/docker-credential-1password b/bash/docker-credential-1password
--- a/bash/docker-credential-1password
+++ b/bash/docker-credential-1password
@@ -30,30 +30,32 @@ function get_vault_id  {
 	result=($(get_docker_vault_ids))
 
 	case ${#result[@]} in
-	 1)
-		echo $result;;
-	 0)
-    return 1;;
-	 *)
-    echo "ERROR: multiple '$DOCKER_CREDENTIAL_1PASSWORD_VAULT' vaults found in 1Password" >&2
-		return 2;;
+		1)
+			echo $result
+			;;
+		0)
+			return 1
+			;;
+		*)
+			echo "ERROR: multiple '$DOCKER_CREDENTIAL_1PASSWORD_VAULT' vaults found in 1Password" >&2
+			return 2;;
 	esac
 }
 
 function get {
-  registry=$(</dev/stdin)
-  vault_id=$(get_vault_id)
-  [[ -z $vault_id ]] && return 0
-  credentials=$(op item get "$registry" \
+	registry=$(</dev/stdin)
+	vault_id=$(get_vault_id)
+	[[ -z $vault_id ]] && return 0
+	credentials=$(op item get "$registry" \
                 --vault "$DOCKER_CREDENTIAL_1PASSWORD_VAULT" --format json 2>/dev/null)
 
-  [[ -z $credentials ]] && return 1
+  	[[ -z $credentials ]] && return 1
 
-  jq --arg registry $registry '{
+  	jq --arg registry $registry '{
 		ServerURL: $registry, 
 		Username: (.fields|map(select(.id == "username")|.value)|.[0]), 
 		Secret: (.fields|map(select(.id == "credential")|.value).[0])
-         }' <<< "$credentials"
+        }' <<< "$credentials"
 }
 
 function erase {
@@ -85,7 +87,7 @@ function list {
 }
 
 function store {
-        body=$(</dev/stdin)
+    body=$(</dev/stdin)
 	url=$(jq -r '.ServerURL' <<< $body)
 	username=$(jq -r '.Username' <<< $body)
 	credential=$(jq -r '.Secret' <<< $body)
@@ -95,7 +97,7 @@ function store {
 	if [[ -z $vault_id ]] && [[ $exit_code == 1 ]]; then
 		vault_id=$(op vault create --format json "$DOCKER_CREDENTIAL_1PASSWORD_VAULT"  </dev/null | jq -r .ID)
 		[[ -z $vault_id ]] && echo "ERROR: failed to create Vault '$DOCKER_CREDENTIAL_1PASSWORD_VAULT'">&2  && exit 1
-  elif [[ -z $vault_id ]]; then
+  	elif [[ -z $vault_id ]]; then
 		exit 1
 	fi
 
@@ -103,44 +105,46 @@ function store {
 	        jq -r --arg title $url 'map(select(.title == $title)|.id)|.[]'))
 	if [[ ${#items[@]} -eq 0 ]]; then
 		op item create --format json \
-		  --title "$url" --category "API Credential" \
-		  --vault "$DOCKER_CREDENTIAL_1PASSWORD_VAULT" -- \
-		  "username=$username" \
-                  "credential=$credential" \
-                  "valid from=$(date +%s)" \
-                  "expires=2147483647" \
-                  </dev/null >/dev/null
+		--title "$url" --category "API Credential" \
+		--vault "$DOCKER_CREDENTIAL_1PASSWORD_VAULT" -- \
+		"username=$username" \
+		"credential=$credential" \
+		"valid from=$(date +%s)" \
+		"expires=2147483647" \
+		</dev/null >/dev/null
 	else
 		op item edit --format json \
-		  "${items[0]}" \
-		  --vault "$DOCKER_CREDENTIAL_1PASSWORD_VAULT" -- \
-		  "username=$username" \
-                  "credential=$credential" \
-                  "valid from=$(date +%s)" \
-                  "expires=2147483647" \
-                  </dev/null >/dev/null
+		    "${items[0]}" \
+		    --vault "$DOCKER_CREDENTIAL_1PASSWORD_VAULT" -- \
+		    "username=$username" \
+            "credential=$credential" \
+            "valid from=$(date +%s)" \
+            "expires=2147483647" \
+            </dev/null >/dev/null
 	fi
 }
 
 function usage {
-		echo "Usage: docker-credential-1password [get|list|store|erase]" >&2
-		echo "$@" >&2
-		exit 1
+	echo "Usage: docker-credential-1password [get|list|store|erase]" >&2
+	echo "$@" >&2
+	exit 1
 }
 
 function main {
-  if ! which jq >/dev/null 2>&1 ; then
-      usage "missing jq on PATH"
-  fi
-  if ! which op >/dev/null 2>&1 ; then
-      usage "missing 1password CLI (op) on PATH"
-  fi
+	if ! which jq >/dev/null 2>&1 ; then
+		usage "missing jq on PATH"
+	fi
+	if ! which op >/dev/null 2>&1 ; then
+		usage "missing 1password CLI (op) on PATH"
+	fi
 
 	case $1 in
-	    list|get|store|erase)
-		eval $1;;
-	    *)
-	    usage "unknown option $1"
+		list|get|store|erase)
+			eval $1
+			;;
+		*)
+			usage "unknown option $1"
+			;;
 	esac
 }
 
