Add protections

diff --git a/bash/docker-credential-1password b/bash/docker-credential-1password
--- a/bash/docker-credential-1password
+++ b/bash/docker-credential-1password
@@ -19,6 +19,17 @@
 # ENVIRONMENT
 #  DOCKER_CREDENTIAL_1PASSWORD_VAULT - name of the 1password vault to use, default Docker
 
+# If expansion is attempted on an unset variable or parameter, the shell prints an
+# error message, and, if not interactive, exits with a non-zero status.
+set -o nounset
+# The pipeline's return status is the value of the last (rightmost) command
+# to exit with a non-zero status, or zero if all commands exit successfully.
+set -o pipefail
+# Enable trace mode if called with environment variable TRACE=1
+if [[ "${TRACE-0}" == "1" ]]; then
+    set -o xtrace
+fi
+
 DOCKER_CREDENTIAL_1PASSWORD_VAULT=${DOCKER_CREDENTIAL_1PASSWORD_VAULT:-Docker}
 
 function get_docker_vault_ids  {
